apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-canara-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canara-app
  template:
    metadata:
      labels:
        app: canara-app
    spec:
      containers:
      - name: canara-app
        image: 714244395551.dkr.ecr.ap-south-1.amazonaws.com/canara
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: canara-app
    k8s-app: canara-app
  name: canara-app
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-app
